### PR TITLE
Fix flexmock fails because of missing typing_extensions

### PR DESCRIPTION
**Pull request by ollipa**
`typing_extensions` should not have been a `dev` dependency because `typing_extensions` is imported during runtime.

### CODE REVIEW

**Comment by ollipa** [comment]
Although, I like that there are no external dependencies. Maybe we should just remove `Literal`?

**Comment by christophe-riolo** [comment]
> Although, I like that there are no external dependencies. Maybe we should just remove `Literal`?

We could probably do that, I'd rather we don't have any runtime dependencies

**Comment by christophe-riolo** [comment]
@ollipa I see that the Literal is used for the integration, and it's not something we can control, so I'd say we don't benefit from it. I am refactoring that module, I'll remove the Literal from there.

**Comment by ollipa** [comment]
Fixed in https://github.com/flexmock/flexmock/pull/12

**Pull request closed without merging**
