### PR TITLE
Fix AttributeError raised when mocking proxied objects

### LINKED ISSUE #81: AttributeError raised when mocking a proxied object
Hello flexmockers.

We discovered an issue with our unit tests which is happening only using latest flexmock `0.10.9` version.

It looks to me that there is a missing condition that suppose to check inside  `_is_static_method(obj, name)` a case when `name` is not exist inside `obj`:
https://github.com/flexmock/flexmock/commit/8df988fe12d24c07f0a05cea750ab72551a9dc0e#diff-4447caeac2a41d5b6017bc003bdcf335c9bef410915b96d38782ee4bd9e81c21R1217

In our case the unit tests started to fail like that after we bumped to 0.10.9  (with 0.10.8 all works great) :

```
venv/lib/python3.6/site-packages/flexmock.py:872: in _get_method_type
    elif _is_static_method(obj, name):
        method     = <bound method Task.delay of <@task: communication.tasks.send_email_tv_package_changed_confirmation of de_complete at 0x7feb7db02278>>
        method_type = None
        name       = 'delay'
        obj        = <@task: communication.tasks.send_email_tv_package_changed_confirmation of de_complete at 0x7feb7db02278>
        self       = <flexmock.Mock object at 0x7feb85e30c88>
venv/lib/python3.6/site-packages/flexmock.py:1217: in _is_static_method
    return isinstance(inspect.getattr_static(obj, name), staticmethod)
        name       = 'delay'
        obj        = <@task: communication.tasks.send_email_tv_package_changed_confirmation of de_complete at 0x7feb7db02278>
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py:1597: in getattr_static
    raise AttributeError(attr)
E   AttributeError: delay
        attr       = 'delay'
        default    = <object object at 0x7feb77d96190>
        dict_attr  = <property object at 0x7feb7ca3a188>
        instance_result = <object object at 0x7feb77d96190>
        klass      = <class 'celery.local.PromiseProxy'>
        klass_result = <object object at 0x7feb77d96190>
        obj        = <@task: communication.tasks.send_email_tv_package_changed_confirmation of de_complete at 0x7feb7db02278>
```

Will try to provide you some more info here about the situation, hopefully it will explain the trouble.
In our code base we have a decorator that wraps our Celery task like that:

```
@celery.task(base=base.tasks.BaseTask, bind=True)
def task_abc(self, some_parameter: int, another_parameter: int):
    result = something_to_do(some_parameter, another_parameter)
    return result
```

and the unit test is looking like that:

```
from flexmock import flexmock
from django.test import TestCase

class TestSomething(TestCase):

    def test_something(self):
        ... some mocking here which works fine
        task_result = flexmock(task_id='123456', id=1)
        flexmock(tasks.task_abc).should_receive('delay').and_return(task_result)
        ... trigger some methods and expect internal Celery method "delay" to be fired up and executed the task_abc
```

Method `delay()` is a part of `celery.app.task.Task` class and our `base.tasks.BaseTask` is inheriting it.

I am not sure about the solution... do not know what should happen inside `flexmock.py:_is_static_method()` method in such cases.

### PR DESCRIPTION
**Pull request by ollipa**
Closes #81 

**TODO**:
- [x] Fix or create an issue: Spying instance method on a proxy object passes wrong `runtime_self`

### CODE REVIEW

**Comment by ollipa** [comment]
@christophe-riolo, do you have an idea why `should_call` with a proxied object passes wrong runtime self to an instance method? This seems to be a very similar bug that you fixed before.

Here is code to reproduce the issue:
```python
from tests.proxy import Proxy
from tests.flexmock_test import SomeClass, DerivedClass
from flexmock import flexmock

ProxySomeClass = Proxy(SomeClass)
instance = ProxySomeClass()
flexmock(instance).should_call("instance_method").and_return("instance_method").once()
assert instance.instance_method() == "instance_method"
```
This raises `AttributeError: 'SomeClass' object has no attribute 'value'`.

**Comment by christophe-riolo** [comment]
> @christophe-riolo, do you have an idea why `should_call` with a proxied object passes wrong runtime self to an instance method? This seems to be a very similar bug that you fixed before.
> 
> Here is code to reproduce the issue:
> 
> ```python
> from tests.proxy import Proxy
> from tests.flexmock_test import SomeClass, DerivedClass
> from flexmock import flexmock
> 
> ProxySomeClass = Proxy(SomeClass)
> instance = ProxySomeClass()
> flexmock(instance).should_call("instance_method").and_return("instance_method").once()
> assert instance.instance_method() == "instance_method"
> ```
> 
> This raises `AttributeError: 'SomeClass' object has no attribute 'value'`.

Hum, I'm not sure but top of my head I'd say it's because `make_method` is not really creating a *method*, bound to the object, it's more like a function emulating a method. I'm not sure, but i'd look that way :thinking:

**Comment by ollipa** [comment]
@christophe-riolo, I had wrong attribute name in the method so it that's why it didn't work :man_facepalming:  This PR is now ready!

**Review by christophe-riolo — APPROVED** [review]
LGTM, let's hope this will fix all :pray:

**Pull request merged**
