### PR TITLE
Rename should_call to should_call_spy

### LINKED ISSUE #86: Rename `Expectation.should_call` method to something more descriptive
I think it would be good to rename `Expectation.should_call` to something more descriptive to distinguish it better from `Expectation.should_receive`. When I did code reviews or wrote tests myself I quite often accidentally used `should_call` (spying) when I should have called `should_receive` (mock) or vice versa.

I suggest that we rename `should_call` to `should_call_spy`. Other suggestions that we discussed before included renaming both methods to something like `call_mock` and `call_spy`. However, I think it's better to make minimal breaking changes to the API.

### PR DESCRIPTION
**Pull request by ollipa**
Closes #86

### CODE REVIEW

**Review by christophe-riolo — APPROVED** [review]
I had doubts about the name still (it's so long), but after thinking about it more I'm fine with it :+1:

**Comment by ollipa** [comment]
@adarshk7, what do you think?

**Comment by adarshk7** [comment]
Added my thoughts to [comment](https://github.com/flexmock/flexmock/issues/86#issuecomment-952053548) on the original issue 😄

**Comment by ollipa** [comment]
I think @adarshk7 made some good points. I'll close this PR and let's continue the discussion in #86 issue.

**Pull request closed without merging**
